### PR TITLE
landing page added

### PR DESCRIPTION
**Pull request by t007rushi**

### CODE REVIEW

**Review by vijaytembugade — APPROVED** [review]
Amazing name. Eye catching. 
Nailed it.

**Review by harshitadaswani — APPROVED** [review]
Good to merge

**Review by JantuDeb — APPROVED** [review]
This is looking good.

**Comment by ultronjs** [comment]
Amazing name.
This is looking good.

**Review by horsemaker — COMMENTED** [review]
looks good!

**Pull request merged**
